CREATE TABLE [User](
  [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  [Name] VARCHAR(255) NOT NULL,
  [Password] VARCHAR(89) NOT NULL,
  [AvailableBalance] MONEY NOT NULL,
  [Document] VARCHAR(14) NOT NULL
)

CREATE TABLE [Stock](
  [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  [Name] VARCHAR(255) NOT NULL,
  [Symbol] VARCHAR(10) NOT NULL,
  [Price] MONEY NOT NULL,
  [Sector] INT NOT NULL,
  [AvailableQuantity] INT NOT NULL
)

CREATE TABLE [Transaction](
  [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  [Amount] INT NOT NULL,
  [Transactiontype] INT NOT NULL,
  [TotalPrice] MONEY NOT NULL,
  [StockId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY([StockId]) REFERENCES [Stock]([Id]),
)

CREATE TABLE [User_Transaction](
  [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  [TransactionId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY([TransactionId]) REFERENCES [Transaction]([Id]),
  [UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY([UserId]) REFERENCES [User]([Id])
)